
    @extends('frontend.layouts.master')
        @section('title')
            BeCarSmart | Privacy Policy
        @endsection
    @section('content')

    <section id="terms-section">
        <div class="row">
            <div class="col-md-12">
                <div class="contact-content text-center mt-5 mb-5">
                    <h2>Privacy Policy</h2>
                </div>
            </div>
        </div>
    </section>

    <!-- Generel Information -->
    <section id="how-to-find" class="terms-condition">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="content-div" style="color: #2c3b53 !important;">
                        <p>We are Be Car Smart Limited. We&rsquo;re a company registered in England and Wales with company number 13739097 whose registered address is at Unit 9, Havant, P09 1HS, in this privacy notice we will refer to ourselves as &lsquo;<strong>we</strong>&rsquo;, &lsquo;<strong>us</strong>&rsquo; or &lsquo;<strong>our</strong>&rsquo;.</p>
<p><strong>You can get hold of us in any of the following ways:</strong></p>
<h5>(a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; by phoning us on 023 935 52653</h5>
<h5>(b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; by e-mailing us at info@becarsmart.co.uk</h5><h5> or</h5>
<p>by writing to us at Basepoint Centre, Unit 9 Harts Farm Way, Havant, PO9 1HS</p>

<p>We take the privacy, including the security, of personal information we hold about you seriously. &nbsp;This privacy notice is designed to inform you about how we collect personal information about you and how we use that personal information.&nbsp; You should read this privacy notice carefully so that you know and can understand why and how we use the personal information we collect and hold about you.</p>
<p>We do not have a Data Protection Officer, but if you have any questions about this privacy notice or issues arising from it then you should contact Mr Jabir Khan, who is responsible for matters relating to data protection at our organisation, including any matters in this privacy notice.&nbsp; You can contact them using the details set out above.</p>
<p>We may issue you with other privacy notices from time to time, including when we collect personal information from you.&nbsp; This privacy notice is intended to supplement these and does not override them.</p>
<p>We may update this privacy notice from time to time. &nbsp;This version was last updated on 20<sup>th</sup> March 2022</p>
<p style='margin:0cm;margin-bottom:.0001pt;text-align:center;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><strong><u><span style='font-size:9px;font-family:"Arial";'><span style="text-decoration:none;">&nbsp;</span></span></u></strong></p>
<div style='margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'>
    <ol style="margin-bottom:0cm;list-style-type: decimal;">
        <li style='margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'>
            <h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><span style='font-family:"Arial";font-size:16px;'>Key Definitions</span></h1>
        </li>
    </ol>
</div>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>The key terms that we use throughout this privacy notice are defined below, for ease:</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><strong><span style='font-size:21px;font-family:"Arial";'>Data Controller</span></strong><strong><span style='font-size:21px;font-family:"Arial";'>:</span></strong><strong><span style='font-size:16px;font-family:"Arial";'>&nbsp;</span></strong><span style='font-size:16px;font-family:"Arial";'>under UK data protection law, this is the organisation or person responsible for deciding how personal information is collected and stored and how it is used. &nbsp;&nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><strong><span style='font-size:21px;font-family:"Arial";'>Data Processor</span></strong><strong><span style='font-size:21px;font-family:"Arial";'>:</span></strong><strong><span style='font-size:16px;font-family:"Arial";'>&nbsp;</span></strong><span style='font-size:16px;font-family:"Arial";'>A Data Controller may appoint another organisation or person to carry out certain tasks in relation to the personal information on behalf of, and on the written instructions of, the Data Controller. (This might be the hosting of a site containing personal data, for example, or providing an email marketing service that facilitates mass distribution of marketing material to a Data Controller&rsquo;s customer-base.)&nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><strong><span style='font-size:21px;font-family:"Arial";'>Personal Information:</span></strong><strong><span style='font-size:16px;font-family:"Arial";'>&nbsp;</span></strong><span style='font-size:16px;font-family:"Arial";'>in this privacy notice we refer to your personal data as &lsquo;personal information&rsquo;. &lsquo;Personal information&rsquo; means any information from which a living individual can be identified. &nbsp;It does not apply to information which has been anonymised.</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><strong><span style='font-size:21px;font-family:"Arial";'>Special Information</span></strong><span style='font-size:16px;font-family:"Arial";'>&nbsp;&ndash; certain very sensitive personal information requires extra protection under data protection law. &nbsp;Sensitive data includes information relating to health, racial and ethnic origin, political opinions, religious and similar beliefs, trade union membership, sex life and sexual orientation and includes genetic information and biometric information. &nbsp;&nbsp;</span></h2>

<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><span style='font-family:"Arial";font-weight:normal;font-size:16px;'>&nbsp; &nbsp; 2. Details of personal information which we collect and hold about you</span></h1>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;2.1. Set out below are the general categories and in each case the types of personal information which we collect, use and hold about you:&nbsp;</span></h2>

<div style='margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'>
    <ol style="margin-bottom:0cm;list-style-type: decimal;">
        <li style='margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'>
            <h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp;</span></h2>
        </li>
    </ol>
</div>
<table style="width:446.55pt;margin-left:-28.6pt;border-collapse:collapse;border: none;">
    <tbody>
        <tr>
            <td style="width: 99.25pt;border: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>General Category&nbsp;</span></strong></h3>
            </td>
            <td style="width: 184.25pt;border-top: 1pt solid windowtext;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-image: initial;border-left: none;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Types of Personal Data in that category&nbsp;</span></strong></h3>
            </td>
            <td style="width: 163.05pt;border-top: 1pt solid windowtext;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-image: initial;border-left: none;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Retention Periods</span></strong></h3>
            </td>
        </tr>
        <tr>
            <td style="width: 99.25pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Identity Information</span></strong></h3>
            </td>
            <td style="width: 184.25pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>This is information relating to your identity such as your name (including any previous names and any titles which you use), gender, marital status and date of birth</span></h3>
            </td>
            <td style="width: 163.05pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>3 Years</span></h3>
            </td>
        </tr>
        <tr>
            <td style="width: 99.25pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Contact Information</span></strong></h3>
            </td>
            <td style="width: 184.25pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>This is information relating to your contact details such as e-mail address, addresses, telephone numbers</span></h3>
            </td>
            <td style="width: 163.05pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>3 Years</span></h3>
            </td>
        </tr>
        <tr>
            <td style="width: 99.25pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Account Information</span></strong></h3>
            </td>
            <td style="width: 184.25pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>This is information relating to your account with us (including username and password</span></h3>
            </td>
            <td style="width: 163.05pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>2 Years after the last date of use</span></h3>
            </td>
        </tr>
        <tr>
            <td style="width: 99.25pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Transaction Information</span></strong></h3>
            </td>
            <td style="width: 184.25pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>This is information relating to transactions between us such as details of the goods, services and/or digital content provided to you and any returns details.</span></h3>
            </td>
            <td style="width: 163.05pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>7 Years</span></h3>
            </td>
        </tr>
        <tr>
            <td style="width: 99.25pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Survey Information</span></strong></h3>
            </td>
            <td style="width: 184.25pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>This is information which we have collected from you or which you have provided to us in respect of surveys and feedback.</span></h3>
            </td>
            <td style="width: 163.05pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>1 year</span></h3>
            </td>
        </tr>
        <tr>
            <td style="width: 99.25pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Marketing Information</span></strong></h3>
            </td>
            <td style="width: 184.25pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>This is information relating to your marketing and communications preferences.</span></h3>
            </td>
            <td style="width: 163.05pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>2 Years after the last date of use</span></h3>
            </td>
        </tr>
        <tr>
            <td style="width: 99.25pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Website, Device and Technical Information</span></strong></h3>
            </td>
            <td style="width: 184.25pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>This is information about your use of our website and technical data which we collect (including your IP address, the type of browser you are using and the version, the operating system you are using, details about the time zone and location settings on the device and other information we receive about your device</span></h3>
            </td>
            <td style="width: 163.05pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>1 Year</span></h3>
            </td>
        </tr>
    </tbody>
</table>

<div style='margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'>
    <h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp;2.2 &nbsp; &nbsp; The types of personal data we collect about you may differ from person to person, depending on who you are and the relationship between us.</span><span style='font-size:16px;font-family:"Arial";'>&nbsp;</span></h2>
</div>
<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><span style='font-family:"Arial";font-weight:normal;font-size:16px;'>&nbsp; &nbsp; 3. Details of special information which we collect and hold about you</span></h1>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp; 3.1 Special information is explained in section&nbsp;</span><span style='font-family:"Arial";font-size:16px;'>1</span><span style='font-family:"Arial";font-size:16px;'>&nbsp;above. &nbsp;We do not collect or hold any special information about you.</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp;3.2 We do not collect information from you relating to criminal convictions or offences.&nbsp;</span></h2>
<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; 4 &nbsp;Details of how and why we use personal information</span><span style='font-family:"Arial";'>&nbsp;</span></h1>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp; 4.1 &nbsp;We are only able to use your personal information for certain legal reasons set out in data protection law. &nbsp;There are legal reasons under data protection law other than those listed below, but in most cases, we will use your personal information for the following legal reasons:&nbsp;</span></h2>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>A) &nbsp;Contract Reason:&nbsp;</span></strong><span style='font-family:"Arial";font-size:16px;'>this is in order to perform our obligations to you under a contract we have entered into with you;&nbsp;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>B) &nbsp;Legitimate Interests Reason</span></strong><span style="font-size:12.0pt;;">: this is where the use of your personal information is necessary for our (or a third party&rsquo;s) legitimate interests, so long as that legitimate interest does not override your fundamental rights, freedoms or interests.&nbsp;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>D) &nbsp;Legal Obligation Reason</span></strong><span style='font-family:"Arial";font-size:16px;'>: this is where we have to use your personal information in order to perform a legal obligation by which we are bound; and&nbsp;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>E) &nbsp; Consent Reason</span></strong><span style='font-family:"Arial";font-size:16px;'>: this is where you have given us your consent to use your personal information for a specific reason or specific reasons.&nbsp;</span></h3>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp;4.2 &nbsp;As explained in section&nbsp;</span><span style='font-family:"Arial";font-size:16px;'>3</span><span style='font-family:"Arial";font-size:16px;'>&nbsp;above, there are more sensitive types of personal data which require higher levels of protection. &nbsp; Where we process such sensitive types of personal data, we will usually do this in the following circumstances:&nbsp;</span></h2>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>a) We have your explicit consent;&nbsp;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>b) Where it is necessary in relation to legal claims</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>c) Where you have made the personal data public</span></h3>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp;4.3 So that we can provide you with services, we will need your personal information. &nbsp;If you do not provide us with the required personal information, we may be prevented from supplying the goods and services</span><span style='font-family:"Arial";font-size:16px;'>&nbsp;to you.</span><span style='font-family:"Arial";'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; 4.4 It is important that you keep your personal information up to date. &nbsp;If any of your personal information changes, please contact us as soon as possible to let us know. &nbsp;If you do not do this then we may be prevented from supplying goods and services (for example, if you move address and do not tell us, then your goods may be delivered to the wrong address).</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; 4.5 Where we rely on consent for a specific purpose as the legal reason for processing your personal information, you have the right under data protection law to withdraw your consent at any time. &nbsp;If you do wish to withdraw your consent, please contact us using the details set out at the beginning of this notice. &nbsp;If we receive a request from you withdrawing your consent to a specific purpose, we will stop processing your personal information for that purpose, unless we have another legal reason for processing your personal information, in which case, we will confirm that reason to you.</span><span style="font-size:12.0pt;;">&nbsp;&nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; 4.6 We have explained below the different purposes for which we use your personal information and, in each case, the legal reason(s) allowing us to use your personal information. &nbsp; Please also note the following:&nbsp;</span><span style='font-family:"Arial";font-size:16px;'><br></span><span style='font-family:"Arial";font-size:16px;'>a) if we use the Legitimate Interests Reason as the legal reason for which we can use your personal information, we have also explained what that legitimate interest is; and&nbsp;</span><br><br><br><span style='font-family:"Arial";font-size:16px;'>b) for some of the purposes we may have listed more than one legal reason on which we can use your personal information, because the legal reason may be different in different circumstances. &nbsp;If you need confirmation of the specific legal reason that we are relying on to use your personal data for that purpose, please contact us using the contact details set out at the start of this privacy notice.&nbsp;</span><br><br></h2>

<div style='margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'>
    <table style="width:446.55pt;margin-left:-28.6pt;border-collapse:collapse;border: none;">
        <tbody>
            <tr>
                <td style="width: 212.65pt;border: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Purpose</span></strong></h3>
                </td>
                <td style="width: 233.9pt;border-top: 1pt solid windowtext;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-image: initial;border-left: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-size:16px;font-family:"Arial";'>Legal Reason(s) for using the personal information&nbsp;</span></strong></h3>
                </td>
            </tr>
            <tr>
                <td style="width: 212.65pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>To enrol you as a customer</span></h3>
                </td>
                <td style="width: 233.9pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Contract Reason.&nbsp;</span></h3>
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Legitimate Interests Reason (in order to offer you other goods, services and/or digital content which helps us to develop our business)</span></h3>
                </td>
            </tr>
            <tr>
                <td style="width: 212.65pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>To process your order, which includes taking payment from you, advising you of any updates in relation to your order or any enforcement action against you to recover payment.</span></h3>
                </td>
                <td style="width: 233.9pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Contract Reason.&nbsp;</span></h3>
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Legitimate Interests Reason (in order to recover money which, you owe us</span></h3>
                </td>
            </tr>
            <tr>
                <td style="width: 212.65pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>To manage our contract with you and to notify you of any changes</span></h3>
                </td>
                <td style="width: 233.9pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Contract Reason.&nbsp;</span></h3>
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Legal Obligation Reason.</span></h3>
                </td>
            </tr>
            <tr>
                <td style="width: 212.65pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>To comply with audit and accounting matters</span></h3>
                </td>
                <td style="width: 233.9pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Legal Obligation Reason</span></h3>
                </td>
            </tr>
            <tr>
                <td style="width: 212.65pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>For record keeping, including in relation to any guarantees or warranties provided as part of the sale of goods, services and/or digital content</span></h3>
                </td>
                <td style="width: 233.9pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Contract Reason.&nbsp;</span></h3>
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Legal Obligation Reason.</span></h3>
                </td>
            </tr>
            <tr>
                <td style="width: 212.65pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>To improve the goods, services, and/or digital content which we supply</span></h3>
                </td>
                <td style="width: 233.9pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Legitimate Interests Reason (in order to improve the goods, services, and/or digital content for future customers and to grow our business</span></h3>
                </td>
            </tr>
            <tr>
                <td style="width: 212.65pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>To recommend and send communications to you about goods, services, and/or digital content that you may be interested in. &nbsp;More details about marketing are set out in section&nbsp;</span><span style='font-size:16px;font-family:"Arial";'>11</span><span style='font-size:16px;font-family:"Arial";'>&nbsp;below</span></h3>
                </td>
                <td style="width: 233.9pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Legitimate Interests Reason (in order to grow our business</span></h3>
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Consent Reason</span></h3>
                </td>
            </tr>
            <tr>
                <td style="width: 212.65pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>To ensure the smooth running and correct operation of our website</span></h3>
                </td>
                <td style="width: 233.9pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Legitimate Interests Reason (to ensure our website runs correctly)</span></h3>
                </td>
            </tr>
            <tr>
                <td style="width: 212.65pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>To understand how customers and visitors to our website use the website and interact with it via data analysis</span></h3>
                </td>
                <td style="width: 233.9pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                    <h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>Legitimate Interests Reason (to improve and grow our business, including our website, and to understand our customer&rsquo;s needs, desires and requirements)</span></h3>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp;4.7 Sometimes we may anonymise personal information so that you can no longer be identified from it and use this for our own purposes. In addition, sometimes we may use some of your personal information together with other people&rsquo;s personal information to give us statistical information for our own purposes. &nbsp;Because this is grouped together wither other personal information and you are not identifiable from that combined data, we are able to use this. &nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp;4.8Under data protection laws we can only use your personal information for the purposes we have told you about, unless we consider that the new purpose is compatible with the purpose(s) which we told you about. &nbsp; If we want to use your personal information for a different purpose which we do not think is compatible with the purpose(s) which we told you about then we will contact you to explain this and what legal reason is in place to allow us to do this.&nbsp;</span></h2>
<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><strong><span style='font-family:"Arial";font-size:16px;'>&nbsp; 5 &nbsp; Details of how we collect personal information and special information</strong></span></h1>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp;5.1 We usually collect Identity Information, Contact Information, Transaction Information, Survey Information, Marketing Information, Special Information; OTHERS directly from you when you fill out a form, survey or questionnaire, purchase goods, services and/or digital content from us, contact us by e-mail, telephone, in writing or otherwise. &nbsp;This includes the personal information which you provide to us when you subscribe to our mailing list enter a competition or survey.&nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp;5.2 &nbsp;We may receive some of your personal information from third parties or publicly available sources. &nbsp;This includes:&nbsp;</span></h2>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>a) &nbsp;Identity Information and Contact Information from publicly available sources such as Companies House.</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>b) &nbsp;Website, Device and Technical Information from third parties such as analytics providers (like Google);&nbsp;</span></h3>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; 5.3&nbsp; We may also receive Website, Device and Technical Information automatically from technologies such as cookies which are installed on our website. &nbsp;To find out more about these please see our cookie policy which is available here.</span></h2>

<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><strong><span style='font-family:"Arial";font-size:16px;'>&nbsp; 6 &nbsp; Details about who personal Information may be shared with</strong></span></h1>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; 6.1 &nbsp;We may need to share your personal information with other organisations or people. &nbsp;These organisations include:&nbsp;</span></h2>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>a) &nbsp;Third parties who are not part of our group. &nbsp;These may include:&nbsp;</span></h3>
<h4 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:4.0cm;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>i)&nbsp; Outside Procurement Partners who will need to contact you in regards to the purchasing of your vehicle</span></h4>
<h4 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:4.0cm;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>ii) Government bodies and regulatory bodies: such as HMRC, fraud prevention agencies, OTHERS who are based in the United Kingdom</span></h4>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>b) any organisations which propose to purchase our business and assets in which case we may disclose your personal information to the potential purchaser.&nbsp;</span></h3>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp;6.2 &nbsp;Depending on the circumstances, the organisations or people who we share your personal information with will be acting as either Data Processors or Data Controllers. &nbsp; Where we share your personal information with a Data Processor, we will ensure that we have in place contracts, which set out the responsibilities and obligations of us and them, including in respect of security of personal information. &nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp;6.3&nbsp; &nbsp;We do not sell or trade any of the personal information which you have provided to us.</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>&nbsp;</span></h2>
<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><strong><span style='font-family:"Arial";font-size:16px;'>&nbsp; 7. &nbsp;  Details about transfers to countries outside of the EEA</strong></span></h1>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;7.1&nbsp; We do not transfer your personal information outside of the EEA.</span></h2>

<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><strong><span style='font-family:"Arial";font-size:16px;'>&nbsp; 8. &nbsp; Details about how long we will hold your personal information</strong></span></h1>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp;8.1 &nbsp;We will only hold your personal data for as long as is necessary. &nbsp;How long is necessary will depend upon the purposes for which we collected the personal information (see section&nbsp;</span><span style='font-family:"Arial";font-size:16px;'>4</span><span style='font-family:"Arial";font-size:16px;'>&nbsp;above) and whether we are under any legal obligation to keep the personal information (such as in relation to accounting or auditing records or for tax reasons). &nbsp; We may also need to keep personal information in case of any legal claims, including in relation to any guarantees or warranties which we have provided with the goods services.</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp;8.2&nbsp; We have set out above the details of our retention periods for different types of data. You can find them in in section&nbsp;</span><span style='font-family:"Arial";font-size:16px;'>2</span><span style='font-family:"Arial";font-size:16px;'>&nbsp;and also in section&nbsp;</span><span style='font-family:"Arial";font-size:16px;'>3</span><span style='font-family:"Arial";font-size:16px;'>.</span></h2>

<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><strong><span style='font-family:"Arial";font-size:16px;'>&nbsp; 9. &nbsp; your rights under data protection law</strong></span></h1>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp;9.1 Under data protection laws you have certain rights in relation to your personal information, as follows:</span></h2>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>a)&nbsp; &nbsp; &nbsp; Right to request access:&nbsp;</span></strong><span style='font-family:"Arial";font-size:16px;'>(this is often called &lsquo;subject access&rsquo;). &nbsp;This is the right to obtain from us a copy of the personal information which we hold about you. We must also provide you with certain other information in response to these requests to help you understand how your personal information is being used.&nbsp;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>b)&nbsp; &nbsp; &nbsp; Right to correction:&nbsp;</span></strong><span style="font-size:12.0pt;;">this is the right to request that any incorrect personal data is corrected and that any incomplete personal data is completed.&nbsp;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>c)&nbsp; &nbsp; Right to erasure:&nbsp;</span></strong><span style='font-family:"Arial";font-size:16px;'>(this is often called the &ldquo;right to be forgotten&rdquo;).<strong>&nbsp;</strong>This right only applies in certain circumstances. &nbsp;Where it does apply, you have the right to request us to erase all of your personal information.&nbsp;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>d) &nbsp;Right to restrict processing:</span></strong><span style='font-family:"Arial";font-size:16px;'>&nbsp;this right only applies in certain circumstances. &nbsp;Where it does apply, you have the right to request us to restrict the processing of your personal information.&nbsp;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>e) &nbsp; &nbsp; Right to data portability:&nbsp;</span></strong><span style="font-size:12.0pt;;">this right allows you to request us to transfer your personal information to someone else.&nbsp;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><strong><span style='font-family:"Arial";font-size:16px;'>f) &nbsp; &nbsp; Right to object:&nbsp;</span></strong><span style='font-family:"Arial";font-size:16px;'>you have the right to object to us processing your personal information for direct marketing purposes. &nbsp;You also have the right to object to us processing personal information where our legal reason for doing so is the Legitimate Interests Reason (see section&nbsp;</span><span style='font-family:"Arial";font-size:16px;'>4</span><span style='font-family:"Arial";font-size:16px;'>&nbsp;above) and there is something about your particular situation which means that you want to object to us processing your personal information. &nbsp;In certain circumstances you have the right to object to processing where such processing consists of profiling (including profiling for direct marketing).&nbsp;</span></h3>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp;9.2&nbsp; In addition to the rights set out in section&nbsp;</span><span style='font-family:"Arial";font-size:16px;'>10.1</span><span style='font-family:"Arial";font-size:16px;'>, where we rely on consent as the legal reason for using your personal information, you have the right to withdraw your consent. &nbsp;Further details about this are set out in section&nbsp;</span><span style='font-family:"Arial";font-size:16px;'>4.5</span><span style='font-family:"Arial";font-size:16px;'>.</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>&nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp;9.3 &nbsp;If you want to exercise any of the above rights in relation to your personal information, please contact us using the details set out at the beginning of this notice. &nbsp;If you do make a request then please note:</span></h2>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>a) &nbsp;we may need certain information from you so that we can verify your identity;</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>b) &nbsp;we do not charge a fee for exercising your rights unless your request is unfounded or excessive; and</span></h3>
<h3 style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:77.95pt;text-align:justify;text-indent:-1.0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>c)&nbsp; &nbsp;if your request is unfounded or excessive then we may refuse to deal with your request.&nbsp;</span></h3>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>&nbsp;</span></h2>
<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><strong><span style='font-family:"Arial";font-size:16px;'>&nbsp; 10. &nbsp; Marketing</strong></span></h1>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp;10.1 You may receive marketing from us about similar goods and services, where either you have consented to this, or we have another legal reason by which we can contact you for marketing purposes.&nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp;  &nbsp; 10.2 However, we will give you the opportunity to manage how or if we market to you. In any e-mail which we send to you, we provide a link to either unsubscribe or opt-out, or to change your marketing preferences. If you have an account with us, you can login to your account and manage your preferences there too. To change your marketing preferences, and/or to request that we stop processing your personal information for marketing purposes, you can always contact us on the details set out at the beginning of this notice.&nbsp;</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; 10.3 If you do request that we stop marketing to you, this will not prevent us from sending communications to you which are not to do with marketing (for example in relation to goods services digital content which you have purchased from us).</span></h2>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-family:"Arial";font-size:16px;'>&nbsp; &nbsp; &nbsp; &nbsp; 10.4 We do not pass your personal information on to any third parties for marketing purposes.&nbsp;</span></h2>

<div style='margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'>
    <h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><strong><span style='font-family:"Arial";font-size:16px;'>&nbsp; 11. &nbsp; Complaints</strong></span></h1>
</div>
<h2 style='margin-top:14.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:36.0pt;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;color:#2c3b53;font-weight:normal;'><span style='font-size:16px;font-family:"Arial";'>If you are unhappy about the way that we have handled or used your personal information, you have the right to complain to the UK supervisory authority for data protection, which is the Information Commissioner&rsquo;s Office (<strong>ICO</strong>). &nbsp;Please do contact us in the first instance if you wish to raise any queries or make a complaint in respect of our handling or use of your personal information, so that we have the opportunity to discuss this with you and to take steps to resolve the position. &nbsp;You can contact us using the details set out at the beginning of this privacy notice.&nbsp;</span></h2>
<div style='margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'>
    <h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:-36.0pt;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><strong><span style='font-family:"Arial";font-size:16px;'>&nbsp; 12. &nbsp;  Third Party Websites</strong></span></h1>
</div>
<h1 style='margin-top:16.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-indent:0cm;line-height:15.0pt;font-size:15px;font-family:"Arial",serif;'><span style='font-size:16px;font-family:"Arial";font-weight:normal;'>Our website may contain links to third party websites. &nbsp;If you click and follow those links then these will take you to the third-party website. &nbsp; Those third-party websites may collect personal information from you and you will need to check their privacy notices to understand how your personal information is collected and used by them.</span></h1>
<p>&nbsp;</p>


                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Suppport Section -->
    <section class="want_to_sell p-3 text-white">
        <div class="container">
            <div class="row">
                <div class="col-md-4 text-center d-flex alignCenter">
                    <p>Want to Sell Your Car?</p>
                </div>
                <div class="col-md-8 float-center">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <form action="{{route('find.vehicle')}}" method="post" class=" formSell d-flex">
                            @csrf
                                <input type="text" name="reg_number" class="form-control" placeholder="AA19AAA" style="padding: 15px;font-size: 22px;font-weight: 600;text-transform: uppercase;">
                                <input type="submit" class="btn btn-danger w-100" value="Value" style="max-width: 35% !important; margin: 0px 0px 0px 20px;background: #2c3b53; ">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @endsection